In [1]:
# Import libraries
## Basic libs
import pandas as pd
import numpy as np
import warnings
## Building Model
from sklearn import linear_model
from scipy import stats
import statsmodels
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
from statsmodels.compat import lzip
## Data Visualization
import seaborn as sb
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.ticker as ticker


# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor

In [2]:
# load dataset
file_path = "../Resources.2/general_dataset.csv"
df= pd.read_csv(file_path)
df.head()

,country_code,country_name,year,agriculture_value_added_constants,agriculture_value_added_percentage_gdp,annual_co2_emissions_tons,inflation_inflation_gdp_deflation,deaths_from_drought,deaths_from_extreme_temps,deaths_from_floods,...,economic_damages_from_storms_as_a_share_of_gdp,economic_damages_from_wildfires,economic_damages_as_a_share_of_gdp,economic_damages,economic_damages_thousands,people_affected_per_100k,number_of_deaths,population_population_growth_annual_percentage,population_population_total,temperature_change_temp_change_celsius
0,AFG,Afghanistan,1971,NaN,NaN,1893554,NaN,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,2.665129,11475450,0.652
1,AFG,Afghanistan,1972,NaN,NaN,1530347,NaN,0.0,0.0,150.0,...,0.0,0.0,0.000000,0.0,0.0,2120.261216,150.0,2.714539,11791222,-1.089
2,AFG,Afghanistan,1976,NaN,NaN,1980859,NaN,0.0,0.0,51.0,...,0.0,0.0,0.000000,0.0,0.0,618.094723,51.0,1.981389,12943093,-0.295
3,AFG,Afghanistan,1978,NaN,NaN,2153300,NaN,0.0,0.0,120.0,...,0.0,0.0,0.393939,52000.0,52000.0,1979.191965,120.0,1.281715,13341199,0.105
4,AFG,Afghanistan,1980,NaN,NaN,1756302,NaN,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,224.601333,0.0,-0.407658,13356500,0.690

In [3]:
hti_df= df[(df['country_name'] == 'Haiti')]
hti_df.head()

,country_code,country_name,year,agriculture_value_added_constants,agriculture_value_added_percentage_gdp,annual_co2_emissions_tons,inflation_inflation_gdp_deflation,deaths_from_drought,deaths_from_extreme_temps,deaths_from_floods,...,economic_damages_from_storms_as_a_share_of_gdp,economic_damages_from_wildfires,economic_damages_as_a_share_of_gdp,economic_damages,economic_damages_thousands,people_affected_per_100k,number_of_deaths,population_population_growth_annual_percentage,population_population_total,temperature_change_temp_change_celsius
1922,HTI,Haiti,1972,NaN,NaN,391721,1.543642,0.0,0.0,78.0,...,0.000000,0.0,0.064449,959.0,959.0,826.958859,78.0,1.670974,4837334,0.324
1923,HTI,Haiti,1974,NaN,NaN,472091,14.504314,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,10131.894484,0.0,1.715022,5003708,-0.189
1924,HTI,Haiti,1977,NaN,NaN,704144,3.883897,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,8498.583569,0.0,1.964309,5294625,0.387
1925,HTI,Haiti,1979,NaN,NaN,749901,3.125091,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,20.108696,8.0,2.126862,5520187,0.133
1926,HTI,Haiti,1980,NaN,NaN,745071,19.263197,0.0,0.0,0.0,...,28.905911,0.0,7.226478,400000.0,400000.0,7673.223463,220.0,2.203511,5643175,0.696

In [4]:
hti_df= hti_df.drop(['country_name'], axis=1)
hti_df.columns.tolist()

['country_code',
 'year',
 'agriculture_value_added_constants',
 'agriculture_value_added_percentage_gdp',
 'annual_co2_emissions_tons',
 'inflation_inflation_gdp_deflation',
 'deaths_from_drought',
 'deaths_from_extreme_temps',
 'deaths_from_floods',
 'deaths_from_storms',
 'deaths_from_wildfires',
 'people_affected_by_drought_per_100k',
 'people_affected_by_extreme_temperatures_per_100k',
 'people_affected_by_floods_per_100k',
 'people_affected_by_storms_per_100k',
 'people_affected_by_wildfires_per_100k',
 'economic_damages_from_drought',
 'economic_damages_from_drought_as_a_share_of_gdp',
 'economic_damages_from_extreme_temperatures',
 'economic_damages_from_extreme_temperatures_as_a_share_of_gdp',
 'economic_damages_from_floods',
 'economic_damages_from_floods_as_a_share_of_gdp',
 'economic_damages_from_storms',
 'economic_damages_from_storms_as_a_share_of_gdp',
 'economic_damages_from_wildfires',
 'economic_damages_as_a_share_of_gdp',
 'economic_damages',
 'economic_damages_thousands',
 'people_affected_per_100k',
 'number_of_deaths',
 'population_population_growth_annual_percentage',
 'population_population_total',
 'temperature_change_temp_change_celsius']

In [5]:
hti_df= hti_df[(hti_df['year'] >= 1988) & (hti_df['year'] <= 2020)]
hti_df.set_index('year',inplace = True)
hti_df.head()

,country_code,agriculture_value_added_constants,agriculture_value_added_percentage_gdp,annual_co2_emissions_tons,inflation_inflation_gdp_deflation,deaths_from_drought,deaths_from_extreme_temps,deaths_from_floods,deaths_from_storms,deaths_from_wildfires,...,economic_damages_from_storms_as_a_share_of_gdp,economic_damages_from_wildfires,economic_damages_as_a_share_of_gdp,economic_damages,economic_damages_thousands,people_affected_per_100k,number_of_deaths,population_population_growth_annual_percentage,population_population_total,temperature_change_temp_change_celsius
year,,,,,,,,,,,,,,,,,,,,,
1988,HTI,2.940172e+09,31.110649,1007669,27.427622,0.0,0.0,27.0,54.0,0.0,...,3.492294,0.0,0.873073,91286.0,91286.0,12928.381178,81.0,2.085452,6758222,0.890
1989,HTI,2.901671e+09,30.592998,1023120,7.820710,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,361.409104,0.0,2.043616,6897755,0.508
1990,HTI,2.780139e+09,29.736751,994997,11.995750,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,2.011597,7037915,0.876
1992,HTI,2.668984e+09,34.120608,888522,20.908166,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,13663.068725,0.0,1.943488,7319491,0.492
1993,HTI,2.710842e+09,30.847043,684199,18.336642,0.0,0.0,13.0,0.0,0.0,...,0.000000,0.0,0.000000,0.0,0.0,67.015145,13.0,1.910631,7460684,0.409

In [6]:
hti_df = hti_df.drop([
 'country_code',
 'deaths_from_drought',
 'deaths_from_extreme_temps',
 'deaths_from_floods',
 'deaths_from_storms',
 'deaths_from_wildfires',
 'people_affected_by_drought_per_100k',
 'people_affected_by_extreme_temperatures_per_100k',
 'people_affected_by_floods_per_100k',
 'people_affected_by_storms_per_100k',
 'people_affected_by_wildfires_per_100k',
 'economic_damages_from_drought',
 'economic_damages_from_drought_as_a_share_of_gdp',
 'economic_damages_from_extreme_temperatures',
 'economic_damages_from_extreme_temperatures_as_a_share_of_gdp',
 'economic_damages_from_floods',
 'economic_damages_from_floods_as_a_share_of_gdp',
 'economic_damages_from_storms',
 'economic_damages_from_storms_as_a_share_of_gdp',
 'economic_damages_from_wildfires',
 'economic_damages',
 'economic_damages_thousands',
], axis=1)
hti_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 1988 to 2020
Data columns (total 10 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   agriculture_value_added_constants               30 non-null     float64
 1   agriculture_value_added_percentage_gdp          30 non-null     float64
 2   annual_co2_emissions_tons                       30 non-null     int64
 3   inflation_inflation_gdp_deflation               30 non-null     float64
 4   economic_damages_as_a_share_of_gdp              30 non-null     float64
 5   people_affected_per_100k                        30 non-null     float64
 6   number_of_deaths                                30 non-null     float64
 7   population_population_growth_annual_percentage  30 non-null     float64
 8   population_population_total                     30 non-null     int64
 9   temperature_change_temp_change_celsius          30 non-null     float64
dtypes: float64(8), int64(2)
memory usage: 2.6 KB

In [7]:
hti_df.columns.tolist()

['agriculture_value_added_constants',
 'agriculture_value_added_percentage_gdp',
 'annual_co2_emissions_tons',
 'inflation_inflation_gdp_deflation',
 'economic_damages_as_a_share_of_gdp',
 'people_affected_per_100k',
 'number_of_deaths',
 'population_population_growth_annual_percentage',
 'population_population_total',
 'temperature_change_temp_change_celsius']

## Modelo 1

In [8]:
# Set independent and dependent variables
X = hti_df[['population_population_total','temperature_change_temp_change_celsius','annual_co2_emissions_tons']]
y = hti_df['economic_damages_as_a_share_of_gdp']

In [9]:
modelo = Sequential()

In [10]:
modelo.add(Dense(1, activation='sigmoid', input_shape=((3,))))

In [11]:
modelo.compile(optimizer='adam', loss='mse',)

In [12]:
historia = modelo.fit(X,y,epochs=100,batch_size=5,verbose=1)

Epoch 1/100
6/6 [==============================] - 0s 835us/step - loss: 0.5763
Epoch 2/100
6/6 [==============================] - 0s 1000us/step - loss: 0.5763
Epoch 3/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5763
Epoch 4/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 5/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5763
Epoch 6/100
6/6 [==============================] - 0s 835us/step - loss: 0.5763
Epoch 7/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 8/100
6/6 [==============================] - 0s 657us/step - loss: 0.5763
Epoch 9/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 10/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 11/100
6/6 [==============================] - 0s 669us/step - loss: 0.5763
Epoch 12/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5763
Epoch 13/100
6/6 [==============================] - 0s 545us/step - loss: 0.5763
Epoch 14/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 15/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 16/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 17/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 18/100
6/6 [==============================] - 0s 707us/step - loss: 0.5763
Epoch 19/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5763
Epoch 20/100
6/6 [==============================] - 0s 868us/step - loss: 0.5763
Epoch 21/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 22/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 23/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 24/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 25/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 26/100
6/6 [==============================] - 0s 666us/step - loss: 0.5763
Epoch 27/100
6/6 [==============================] - 0s 669us/step - loss: 0.5763
Epoch 28/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 29/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 30/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 31/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 32/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 33/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 34/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5763
Epoch 35/100
6/6 [==============================] - 0s 668us/step - loss: 0.5763
Epoch 36/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 37/100
6/6 [==============================] - 0s 334us/step - loss: 0.5763
Epoch 38/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 39/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 40/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 41/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 42/100
6/6 [==============================] - 0s 503us/step - loss: 0.5763
Epoch 43/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 44/100
6/6 [==============================] - 0s 689us/step - loss: 0.5763
Epoch 45/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 46/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 47/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 48/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 49/100
6/6 [==============================] - 0s 516us/step - loss: 0.5763
Epoch 50/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 51/100
6/6 [==============================] - 0s 727us/step - loss: 0.5763
Epoch 52/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 53/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 54/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 55/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 56/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 57/100
6/6 [==============================] - 0s 781us/step - loss: 0.5763
Epoch 58/100
6/6 [==============================] - 0s 498us/step - loss: 0.5763
Epoch 59/100
6/6 [==============================] - 0s 358us/step - loss: 0.5763
Epoch 60/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 61/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 62/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 63/100
6/6 [==============================] - 0s 834us/step - loss: 0.5763
Epoch 64/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 65/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 66/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 67/100
6/6 [==============================] - 0s 334us/step - loss: 0.5763
Epoch 68/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 69/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 70/100
6/6 [==============================] - 0s 1000us/step - loss: 0.5763
Epoch 71/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 72/100
6/6 [==============================] - 0s 332us/step - loss: 0.5763
Epoch 73/100
6/6 [==============================] - 0s 511us/step - loss: 0.5763
Epoch 74/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 75/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 76/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 77/100
6/6 [==============================] - 0s 1ms/step - loss: 0.5763
Epoch 78/100
6/6 [==============================] - 0s 355us/step - loss: 0.5763
Epoch 79/100
6/6 [==============================] - 0s 334us/step - loss: 0.5763
Epoch 80/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 81/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 82/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 83/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 84/100
6/6 [==============================] - 0s 834us/step - loss: 0.5763
Epoch 85/100
6/6 [==============================] - 0s 3ms/step - loss: 0.5763
Epoch 86/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 87/100
6/6 [==============================] - 0s 666us/step - loss: 0.5763
Epoch 88/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 89/100
6/6 [==============================] - 0s 332us/step - loss: 0.5763
Epoch 90/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 91/100
6/6 [==============================] - 0s 833us/step - loss: 0.5763
Epoch 92/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 93/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 94/100
6/6 [==============================] - 0s 667us/step - loss: 0.5763
Epoch 95/100
6/6 [==============================] - 0s 512us/step - loss: 0.5763
Epoch 96/100
6/6 [==============================] - 0s 333us/step - loss: 0.5763
Epoch 97/100
6/6 [==============================] - 0s 499us/step - loss: 0.5763
Epoch 98/100
6/6 [==============================] - 0s 833us/step - loss: 0.5763
Epoch 99/100
6/6 [==============================] - 0s 500us/step - loss: 0.5763
Epoch 100/100
6/6 [==============================] - 0s 334us/step - loss: 0.5763

In [13]:
# Evaluate the model 
model_loss= modelo.evaluate(X,y,verbose=2)
print(f"Loss: {model_loss}")

1/1 - 0s - loss: 0.5763
Loss: 0.5762558579444885

In [14]:
predictions = modelo.predict(X)

In [15]:
print(predictions)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

MODELO 2

In [16]:
# Set independent and dependent variables
X = hti_df[['population_population_total','temperature_change_temp_change_celsius','annual_co2_emissions_tons']]
y = hti_df['economic_damages_as_a_share_of_gdp']
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [17]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
# Define the model - deep neural net

hidden_nodes_layer1 = 4
hidden_nodes_layer2 =2

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=(3), activation="tanh")
)

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 4)                 16
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 5
=================================================================
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________

In [19]:
# Compile the model
nn.compile(loss="mse", optimizer="adam", metrics=["accuracy"])

In [20]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2412 - accuracy: 0.2727
Epoch 2/100
1/1 [==============================] - 0s 999us/step - loss: 0.2407 - accuracy: 0.2727
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2401 - accuracy: 0.2727
Epoch 4/100
1/1 [==============================] - 0s 999us/step - loss: 0.2396 - accuracy: 0.2727
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2391 - accuracy: 0.2727
Epoch 6/100
1/1 [==============================] - 0s 983us/step - loss: 0.2385 - accuracy: 0.2727
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2380 - accuracy: 0.2727
Epoch 8/100
1/1 [==============================] - 0s 994us/step - loss: 0.2375 - accuracy: 0.2727
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2370 - accuracy: 0.2727
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2365 - accuracy: 0.2727
Epoch 11/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2360 - accuracy: 0.2727
Epoch 12/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2354 - accuracy: 0.3182
Epoch 13/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2349 - accuracy: 0.3182
Epoch 14/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2344 - accuracy: 0.3182
Epoch 15/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2339 - accuracy: 0.3182
Epoch 16/100
1/1 [==============================] - 0s 952us/step - loss: 0.2334 - accuracy: 0.3182
Epoch 17/100
1/1 [==============================] - 0s 956us/step - loss: 0.2330 - accuracy: 0.3182
Epoch 18/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2325 - accuracy: 0.3182
Epoch 19/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2320 - accuracy: 0.3182
Epoch 20/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2315 - accuracy: 0.3182
Epoch 21/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2310 - accuracy: 0.3182
Epoch 22/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2305 - accuracy: 0.3182
Epoch 23/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2301 - accuracy: 0.3636
Epoch 24/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2296 - accuracy: 0.3636
Epoch 25/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2291 - accuracy: 0.3636
Epoch 26/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2287 - accuracy: 0.3636
Epoch 27/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2282 - accuracy: 0.3636
Epoch 28/100
1/1 [==============================] - 0s 998us/step - loss: 0.2277 - accuracy: 0.3636
Epoch 29/100
1/1 [==============================] - 0s 999us/step - loss: 0.2273 - accuracy: 0.3636
Epoch 30/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2268 - accuracy: 0.3636
Epoch 31/100
1/1 [==============================] - 0s 0s/step - loss: 0.2264 - accuracy: 0.3636
Epoch 32/100
1/1 [==============================] - 0s 999us/step - loss: 0.2259 - accuracy: 0.3636
Epoch 33/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2255 - accuracy: 0.3636
Epoch 34/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2250 - accuracy: 0.3636
Epoch 35/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2246 - accuracy: 0.3636
Epoch 36/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2241 - accuracy: 0.3636
Epoch 37/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2237 - accuracy: 0.3636
Epoch 38/100
1/1 [==============================] - 0s 994us/step - loss: 0.2233 - accuracy: 0.3636
Epoch 39/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2228 - accuracy: 0.3636
Epoch 40/100
1/1 [==============================] - 0s 3ms/step - loss: 0.2224 - accuracy: 0.3636
Epoch 41/100
1/1 [==============================] - 0s 0s/step - loss: 0.2220 - accuracy: 0.3636
Epoch 42/100
1/1 [==============================] - 0s 988us/step - loss: 0.2215 - accuracy: 0.3636
Epoch 43/100
1/1 [==============================] - 0s 993us/step - loss: 0.2211 - accuracy: 0.3636
Epoch 44/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2207 - accuracy: 0.3636
Epoch 45/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2202 - accuracy: 0.3636
Epoch 46/100
1/1 [==============================] - 0s 0s/step - loss: 0.2198 - accuracy: 0.4091
Epoch 47/100
1/1 [==============================] - 0s 949us/step - loss: 0.2194 - accuracy: 0.4091
Epoch 48/100
1/1 [==============================] - 0s 914us/step - loss: 0.2189 - accuracy: 0.4091
Epoch 49/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2185 - accuracy: 0.4091
Epoch 50/100
1/1 [==============================] - 0s 0s/step - loss: 0.2181 - accuracy: 0.4091
Epoch 51/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2177 - accuracy: 0.4091
Epoch 52/100
1/1 [==============================] - 0s 0s/step - loss: 0.2172 - accuracy: 0.4091
Epoch 53/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2168 - accuracy: 0.4091
Epoch 54/100
1/1 [==============================] - 0s 0s/step - loss: 0.2164 - accuracy: 0.4091
Epoch 55/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2160 - accuracy: 0.4091
Epoch 56/100
1/1 [==============================] - 0s 500us/step - loss: 0.2156 - accuracy: 0.4091
Epoch 57/100
1/1 [==============================] - 0s 500us/step - loss: 0.2151 - accuracy: 0.4091
Epoch 58/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2147 - accuracy: 0.4091
Epoch 59/100
1/1 [==============================] - 0s 0s/step - loss: 0.2143 - accuracy: 0.4091
Epoch 60/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2139 - accuracy: 0.4091
Epoch 61/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2134 - accuracy: 0.4091
Epoch 62/100
1/1 [==============================] - 0s 0s/step - loss: 0.2130 - accuracy: 0.4091
Epoch 63/100
1/1 [==============================] - 0s 999us/step - loss: 0.2126 - accuracy: 0.4091
Epoch 64/100
1/1 [==============================] - 0s 499us/step - loss: 0.2122 - accuracy: 0.4091
Epoch 65/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2117 - accuracy: 0.4091
Epoch 66/100
1/1 [==============================] - 0s 686us/step - loss: 0.2113 - accuracy: 0.4091
Epoch 67/100
1/1 [==============================] - 0s 971us/step - loss: 0.2109 - accuracy: 0.4091
Epoch 68/100
1/1 [==============================] - 0s 498us/step - loss: 0.2105 - accuracy: 0.4091
Epoch 69/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2100 - accuracy: 0.4091
Epoch 70/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2096 - accuracy: 0.4091
Epoch 71/100
1/1 [==============================] - 0s 0s/step - loss: 0.2092 - accuracy: 0.4091
Epoch 72/100
1/1 [==============================] - 0s 0s/step - loss: 0.2088 - accuracy: 0.4091
Epoch 73/100
1/1 [==============================] - 0s 0s/step - loss: 0.2083 - accuracy: 0.4091
Epoch 74/100
1/1 [==============================] - 0s 0s/step - loss: 0.2079 - accuracy: 0.4091
Epoch 75/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2075 - accuracy: 0.4091
Epoch 76/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2071 - accuracy: 0.4545
Epoch 77/100
1/1 [==============================] - 0s 0s/step - loss: 0.2066 - accuracy: 0.4545
Epoch 78/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2062 - accuracy: 0.5000
Epoch 79/100
1/1 [==============================] - 0s 998us/step - loss: 0.2058 - accuracy: 0.5000
Epoch 80/100
1/1 [==============================] - 0s 0s/step - loss: 0.2054 - accuracy: 0.5000
Epoch 81/100
1/1 [==============================] - 0s 997us/step - loss: 0.2049 - accuracy: 0.5000
Epoch 82/100
1/1 [==============================] - 0s 0s/step - loss: 0.2045 - accuracy: 0.5000
Epoch 83/100
1/1 [==============================] - 0s 999us/step - loss: 0.2041 - accuracy: 0.5000
Epoch 84/100

1/1 [==============================] - 0s 990us/step - loss: 0.2036 - accuracy: 0.5455
Epoch 85/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2032 - accuracy: 0.5455
Epoch 86/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2028 - accuracy: 0.5455
Epoch 87/100
1/1 [==============================] - 0s 1000us/step - loss: 0.2023 - accuracy: 0.5455
Epoch 88/100
1/1 [==============================] - 0s 0s/step - loss: 0.2019 - accuracy: 0.5455
Epoch 89/100
1/1 [==============================] - 0s 1ms/step - loss: 0.2015 - accuracy: 0.5455
Epoch 90/100
1/1 [==============================] - 0s 998us/step - loss: 0.2010 - accuracy: 0.5455
Epoch 91/100
1/1 [==============================] - 0s 0s/step - loss: 0.2006 - accuracy: 0.5455
Epoch 92/100
1/1 [==============================] - 0s 0s/step - loss: 0.2002 - accuracy: 0.5455
Epoch 93/100
1/1 [==============================] - 0s 0s/step - loss: 0.1997 - accuracy: 0.5455
Epoch 94/100
1/1 [==============================] - 0s 1000us/step - loss: 0.1993 - accuracy: 0.5455
Epoch 95/100
1/1 [==============================] - 0s 1000us/step - loss: 0.1989 - accuracy: 0.5455
Epoch 96/100
1/1 [==============================] - 0s 0s/step - loss: 0.1984 - accuracy: 0.5455
Epoch 97/100
1/1 [==============================] - 0s 2ms/step - loss: 0.1980 - accuracy: 0.5455
Epoch 98/100
1/1 [==============================] - 0s 0s/step - loss: 0.1976 - accuracy: 0.5455
Epoch 99/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1971 - accuracy: 0.5455
Epoch 100/100
1/1 [==============================] - 0s 0s/step - loss: 0.1967 - accuracy: 0.5455

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

1/1 - 0s - loss: 1.5895 - accuracy: 0.7500
Loss: 1.5894930362701416, Accuracy: 0.75

In [22]:
predictions_nn = nn.predict(X)

In [23]:
print(predictions_nn)

[[0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]
 [0.3748673]]

MODELO 3